spring:
  application:
    name: FEED
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feed_system_10?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 2048711712P!
dubbo:
  protocol:
    name: dubbo
    port: -1
    serialization: fastjson2
  registry:
    address: nacos://127.0.0.1:8848
server:
  port: 22003
