name: Java CI with Maven

# 触发条件：当代码推送到特定分支时触发（如 main 分支）
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

# 定义工作流的执行步骤
jobs:
  build:
    # 定义运行环境
    runs-on: ubuntu-latest

    # 定义任务步骤
    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 JDK 版本
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # 项目使用的 Java 版本
          distribution: 'temurin'

      # Step 3: 缓存 Maven 依赖，加速构建
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: 使用 Maven 构建项目
      - name: Build with Maven
        run: mvn clean install

      # Step 5: 运行测试
      - name: Run tests
        run: mvn test